[package]
name = "music-player"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.18.0"
gtk = { package = "gtk4", version = "0.6.6", features = ["v4_10"] }
diesel = { version = "2.1.0", features = ["sqlite"] }
dotenvy = { version = "0.15.7" }
