[package]
name = "music-player"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
log = "0.4.18"
std-logger = "0.5.2"
once_cell = "1.18.0"
gtk = { package = "gtk4", version = "0.6.6", features = ["v4_10"] }
diesel = { version = "2.1.0", features = ["r2d2", "sqlite", "returning_clauses_for_sqlite_3_35"] }
diesel_migrations = "2.1.0"
walkdir = "2.3.3"
gstreamer = "0.20.6"
gstreamer-pbutils = "0.20.6"
